### PR TITLE
Fix and optimize queries

### LINKED ISSUE #67: Inconsistent ordering
Reproduce:
```
❯ curl -H "Authorization: Bearer $API_TOKEN" 'https://token-api.thegraph.com/transfers/evm?contract=0x8eea6cc08d824b20efb3bf7c248de694cb1f75f4' \
| jq '[.data[].datetime]'

[
  "2025-04-28 18:22:35",
  "2025-04-28 18:21:23",
  "2025-04-28 18:20:59",
  "2025-04-28 18:20:11",
  "2025-04-28 18:06:23",
  "2025-04-28 18:14:23",
  "2025-04-28 18:13:35",
  "2025-04-28 18:00:59",
  "2025-04-28 17:59:11",
  "2025-04-28 18:25:47"
]
```

Results are shuffled and not properly ordered.

### PR DESCRIPTION
**Pull request by YaroShkvorets**
- Add ordering to results to avoid re-shuffling rows from subqueries - fixes #67
- Remove `FINAL` from `contracts` queries since this table is pretty static and doesn't need FINAL on every query

### CODE REVIEW

File: src/sql/transfers/evm.sql [hunk 1]
```diff
@@ -54,3 +54,4 @@ FROM t
 LEFT JOIN contracts AS c ON c.address = t.contract
     AND ({contract:String} = '' OR c.address = {contract:String})
 WHERE isNotNull(decimals)
+ORDER BY timestamp DESC
```
Comment (DenisCarriere) [inline src/sql/transfers/evm.sql:57]: Isn't the ordering already happening here?

https://github.com/pinax-network/token-api/pull/68/files#diff-cabf8fd481ab850f9d0ec1e706ff4dffe8f39351e5d49a7cad54ae63a2fdbf67R37

File: src/sql/swaps/evm.sql [hunk 2]
```diff
@@ -49,3 +49,4 @@ JOIN pools      AS p ON p.pool = s.pool
     AND ({protocol:String}   = '' OR p.protocol       = {protocol:String})
 JOIN contracts  AS c0 ON c0.address = p.token0
 JOIN contracts  AS c1 ON c1.address = p.token1
+ORDER BY timestamp DESC
```
Comment (DenisCarriere) [inline src/sql/swaps/evm.sql:52]: Isn't the ordering already happening here?

https://github.com/pinax-network/token-api/pull/68/files#diff-65df69b4efb70c35423b3e6fd8730e6146041c3e74815de6ab44664e0e084359L22

Comment (YaroShkvorets) [reply src/sql/swaps/evm.sql:52]: It's re-shuffling after JOIN. See example here: https://github.com/pinax-network/token-api/issues/67
This "ORDER BY" is very light since we are only sorting "LIMIT" rows.
